import json
import tempfile
import unittest
from pathlib import Path

from nbs2func.cli import sanitize_datapack_name
from nbs2func.command_writer import BasicMcfunctionWriter, CommandWriterConfig
from nbs2func.layout import BlockPosition, LayoutCell, LayoutResult
from nbs2func.minecraft_version import (
    JAVA_1_16_5,
    MinecraftVersionError,
    get_minecraft_version_profile,
    get_version_profile,
)


class DatapackOutputTest(unittest.TestCase):
    def test_split_output_writes_pack_mcmeta_and_build_functions(self) -> None:
        layout = LayoutResult(
            mode="test",
            cells=(_cell(0),),
            notes=(),
            conflicts=(),
        )

        with tempfile.TemporaryDirectory() as tmp_dir:
            datapack_root = Path(tmp_dir) / "my_song"
            BasicMcfunctionWriter(
                CommandWriterConfig(
                    split_functions=True,
                    minecraft_version_profile=JAVA_1_16_5,
                )
            ).write_file(layout, datapack_root)

            pack_mcmeta = datapack_root / "pack.mcmeta"
            build_dir = datapack_root / "data" / "nbs" / "functions" / "build"

            self.assertTrue(pack_mcmeta.exists())
            self.assertEqual(
                json.loads(pack_mcmeta.read_text(encoding="utf-8")),
                {
                    "pack": {
                        "pack_format": 6,
                        "description": (
                            "Generated by nbs2func for Minecraft Java 1.16.5"
                        ),
                    }
                },
            )
            self.assertTrue((build_dir / "start.mcfunction").exists())

    def test_sanitize_datapack_name_handles_spaces_and_special_chars(self) -> None:
        self.assertEqual(
            sanitize_datapack_name("My Cool Song!! 2026"),
            "my_cool_song_2026",
        )
        self.assertEqual(sanitize_datapack_name("___"), "nbs_song")

    def test_java_1_16_5_profile_uses_legacy_function_directories(self) -> None:
        profile = get_version_profile("1.16.5")

        self.assertEqual(profile.version, "1.16.5")
        self.assertEqual(profile.version_id, "1.16.5")
        self.assertEqual(profile.pack_format, 6)
        self.assertEqual(profile.namespace, "nbs")
        self.assertEqual(profile.function_dir_name, "functions")
        self.assertEqual(profile.function_tag_dir_name, "functions")

    def test_default_minecraft_profile_is_java_1_16_5(self) -> None:
        self.assertEqual(get_minecraft_version_profile(None).version_id, "1.16.5")
        self.assertEqual(get_minecraft_version_profile("").version_id, "1.16.5")

    def test_minecraft_version_exact_profiles_and_aliases(self) -> None:
        self.assertEqual(
            get_minecraft_version_profile("1.16.5").version_id,
            "1.16.5",
        )
        self.assertEqual(
            get_minecraft_version_profile("1.16").version_id,
            "1.16.5",
        )
        self.assertEqual(
            get_minecraft_version_profile("1.20").version_id,
            "1.20.1",
        )

    def test_unknown_minecraft_version_raises_clear_error(self) -> None:
        with self.assertRaises(MinecraftVersionError) as context:
            get_minecraft_version_profile("1.12.2")

        message = str(context.exception)
        self.assertIn("1.12.2", message)
        self.assertIn("1.16.5", message)
        self.assertIn("1.16", message)
        self.assertIn("Aliases select a specific profile", message)


def _cell(tick: int) -> LayoutCell:
    x = tick * 2
    return LayoutCell(
        tick=tick,
        track_id="0",
        source_track_id=0,
        repeater_position=BlockPosition(x, 128, 0),
        repeater_facing="west",
        track_block_position=BlockPosition(x, 127, 0),
        note_block_position=BlockPosition(x - 1, 128, 0),
        instrument_block_position=BlockPosition(x - 1, 127, 0),
        note=None,
    )


if __name__ == "__main__":
    unittest.main()
