from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path


@dataclass(frozen=True)
class MinecraftVersionProfile:
    version: str
    pack_format: int
    namespace: str
    function_dir_name: str
    function_tag_dir_name: str


JAVA_1_16_5 = MinecraftVersionProfile(
    version="1.16.5",
    pack_format=6,
    namespace="nbs",
    function_dir_name="functions",
    function_tag_dir_name="functions",
)


def get_version_profile(version: str) -> MinecraftVersionProfile:
    if version == JAVA_1_16_5.version:
        return JAVA_1_16_5
    raise ValueError(f"Unsupported Minecraft Java version: {version}")


def write_pack_mcmeta(
    datapack_root: Path,
    profile: MinecraftVersionProfile,
    description: str | None = None,
) -> None:
    datapack_root.mkdir(parents=True, exist_ok=True)
    pack_description = (
        description
        if description is not None
        else f"Generated by nbs2func for Minecraft Java {profile.version}"
    )
    data = {
        "pack": {
            "pack_format": profile.pack_format,
            "description": pack_description,
        }
    }
    (datapack_root / "pack.mcmeta").write_text(
        json.dumps(data, indent=2) + "\n",
        encoding="utf-8",
    )
