from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .layout import DIRECTION_VECTORS, BlockPosition, LayoutResult, normalize_direction

DEFAULT_START_MUSIC_COUNT = 10
VEHICLE_STEP_DISTANCE = 1
COMMAND_MODULE_FACING = "east"


@dataclass(frozen=True)
class PlaybackAssistModuleConfig:
    """Configuration skeleton for an optional in-world playback helper."""

    enable_playback_assist: bool = False
    player_name: str = "Alex842036"
    playback_vehicle_tag: str = "playback_vehicle"
    starter_tag: str = "nbs_starter"
    count_objective: str = "count"
    vehicle_spawn_position: BlockPosition | None = None
    music_start_position: BlockPosition = BlockPosition(0, 128, 0)
    command_module_origin: BlockPosition | None = None
    track_direction: str = "east"
    total_track_length: int = 20
    generate_playback_buttons: bool = True
    playback_button_block: str = "minecraft:stone_button"
    prepare_button_position: BlockPosition | None = None
    start_button_position: BlockPosition | None = None


@dataclass(frozen=True)
class PlaybackAssistDebugInfo:
    prepare_command_block_position: BlockPosition
    prepare_button_position: BlockPosition
    start_command_block_position: BlockPosition
    start_button_position: BlockPosition
    vehicle_spawn_position: BlockPosition
    music_start_position: BlockPosition
    track_direction: str
    yaw: int
    start_music_count: int
    end_count: int
    total_track_length: int
    command_module_origin: BlockPosition


YAW_BY_DIRECTION = {
    "east": -90,
    "west": 90,
    "south": 0,
    "north": 180,
}


def playback_assist_lines(config: PlaybackAssistModuleConfig) -> list[str]:
    """Return mcfunction lines for the minimal playback assist module."""

    if not config.enable_playback_assist:
        return []
    if not config.player_name:
        raise ValueError("player_name is required when playback assist is enabled.")

    debug = playback_assist_debug_info(config)
    prepare_commands = _prepare_chain_commands(config, debug)
    start_command = _relative_setblock_command(
        debug.start_command_block_position,
        _local_position(config, 0, 1),
        "redstone_block",
    )

    lines = [
        "# Generated by nbs2func playback assist module",
        "# This module builds command blocks for minecart playback assist.",
        "# Press Prepare, enter the minecart, then press Start.",
        "",
        "# one-time scoreboard objective setup",
        f"scoreboard objectives add {config.count_objective} dummy",
        "",
        "# tp-loop command blocks",
        _setblock(
            _local_position(config, 0, 0),
            _command_block("clone ~ ~1 ~ ~ ~1 ~ ~1 ~1 ~ masked move"),
        ),
        _setblock(
            _local_position(config, 1, 0),
            _command_block("clone ~ ~1 ~ ~ ~1 ~ ~-1 ~1 ~ masked move"),
        ),
        "",
        "# move the minecart by 0.5 blocks on each half-loop",
        _setblock(_local_position(config, 0, 2), _command_block(_tp_vehicle(config))),
        _setblock(_local_position(config, 1, 2), _command_block(_tp_vehicle(config))),
        "",
        "# count once per full loop; start music at start_music; stop at end",
        _setblock(
            _local_position(config, 2, 1),
            _command_block(
                f"scoreboard players add {config.player_name} "
                f"{config.count_objective} 1",
                facing="up",
            ),
        ),
        _setblock(
            _local_position(config, 2, 2),
            _chain_command_block(
                "execute if score "
                f"{config.player_name} {config.count_objective} = "
                f"end {config.count_objective} run clone "
                "~-1 ~-1 ~ ~-1 ~-1 ~ ~-2 ~-1 ~2 replace move",
                facing="up",
                auto=True,
            ),
        ),
        _setblock(
            _local_position(config, 2, 3),
            _chain_command_block(
                "execute if score "
                f"{config.player_name} {config.count_objective} = "
                f"start_music {config.count_objective} run execute as "
                f"@e[type=minecraft:armor_stand,tag={config.starter_tag}] "
                "at @s run setblock ~ ~ ~ minecraft:redstone_block",
                facing="up",
                auto=True,
            ),
        ),
        _setblock(
            _local_position(config, 2, 4),
            _chain_command_block(
                "execute if score "
                f"{config.player_name} {config.count_objective} = "
                f"start_music {config.count_objective} run execute as "
                f"@e[type=minecraft:armor_stand,tag={config.starter_tag}] "
                "at @s run setblock ~ ~ ~ air",
                facing="up",
                auto=True,
            ),
        ),
        "",
        "# Prepare command chain: reset state and summon the minecart, but do not start movement.",
    ]
    for index, command in enumerate(prepare_commands):
        position = _local_position(config, index, -2)
        if index == 0:
            block = _command_block(command, facing=COMMAND_MODULE_FACING)
        else:
            block = _chain_command_block(
                command,
                facing=COMMAND_MODULE_FACING,
                auto=True,
            )
        lines.append(_setblock(position, block))

    lines.extend(
        [
            "",
            "# Start command block: press after entering the minecart.",
            _setblock(
                debug.start_command_block_position,
                _command_block(start_command, facing=COMMAND_MODULE_FACING),
            ),
        ]
    )

    if config.generate_playback_buttons:
        lines.extend(
            [
                "",
                "# Playback buttons",
                _setblock(
                    debug.prepare_button_position,
                    _button_block(
                        config.playback_button_block,
                        COMMAND_MODULE_FACING,
                    ),
                ),
                _setblock(
                    debug.start_button_position,
                    _button_block(
                        config.playback_button_block,
                        COMMAND_MODULE_FACING,
                    ),
                ),
            ]
        )

    lines.extend(
        [
            "",
            "# Press the Prepare button, enter the minecart, then press Start.",
        ]
    )
    return lines


def write_playback_assist_file(
    config: PlaybackAssistModuleConfig,
    path: str | Path,
) -> None:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(playback_assist_lines(config)) + "\n", encoding="utf-8")


def playback_assist_debug_info(
    config: PlaybackAssistModuleConfig,
) -> PlaybackAssistDebugInfo:
    start_count = start_music_count(config)
    total_track_length = max(0, config.total_track_length)
    direction = normalize_direction(config.track_direction)
    prepare_command = prepare_command_block_position(config)
    start_command = start_command_block_position(config)
    vehicle_spawn = resolved_vehicle_spawn_position(config)
    command_module_origin = resolved_command_module_origin(config)
    return PlaybackAssistDebugInfo(
        prepare_command_block_position=prepare_command,
        prepare_button_position=(
            config.prepare_button_position or above(prepare_command)
        ),
        start_command_block_position=start_command,
        start_button_position=config.start_button_position or above(start_command),
        vehicle_spawn_position=vehicle_spawn,
        music_start_position=config.music_start_position,
        track_direction=direction,
        yaw=YAW_BY_DIRECTION[direction],
        start_music_count=start_count,
        end_count=start_count + total_track_length,
        total_track_length=total_track_length,
        command_module_origin=command_module_origin,
    )


def resolved_vehicle_spawn_position(config: PlaybackAssistModuleConfig) -> BlockPosition:
    if config.vehicle_spawn_position is not None:
        return config.vehicle_spawn_position
    return default_vehicle_spawn_position(
        config.music_start_position,
        config.track_direction,
        DEFAULT_START_MUSIC_COUNT,
    )


def default_vehicle_spawn_position(
    music_start_position: BlockPosition,
    track_direction: str,
    start_music_count: int = DEFAULT_START_MUSIC_COUNT,
) -> BlockPosition:
    dx, dz = DIRECTION_VECTORS[normalize_direction(track_direction)]
    distance = start_music_count * VEHICLE_STEP_DISTANCE
    return BlockPosition(
        music_start_position.x - dx * distance,
        music_start_position.y,
        music_start_position.z - dz * distance,
    )


def resolved_command_module_origin(config: PlaybackAssistModuleConfig) -> BlockPosition:
    if config.command_module_origin is not None:
        return config.command_module_origin
    return default_command_module_origin(
        config.music_start_position,
        config.track_direction,
    )


def default_command_module_origin(
    music_start_position: BlockPosition,
    track_direction: str,
    distance: int = 15,
) -> BlockPosition:
    dx, dz = DIRECTION_VECTORS[normalize_direction(track_direction)]
    return BlockPosition(
        music_start_position.x - dx * distance,
        music_start_position.y,
        music_start_position.z - dz * distance,
    )


def prepare_command_block_position(
    config: PlaybackAssistModuleConfig,
) -> BlockPosition:
    return _local_position(config, 0, -2)


def start_command_block_position(
    config: PlaybackAssistModuleConfig,
) -> BlockPosition:
    direction = normalize_direction(config.track_direction)
    dx, dz = DIRECTION_VECTORS[direction]
    vehicle = resolved_vehicle_spawn_position(config)
    return BlockPosition(vehicle.x + dx, vehicle.y, vehicle.z + dz)


def start_music_count(config: PlaybackAssistModuleConfig) -> int:
    direction = normalize_direction(config.track_direction)
    dx, dz = DIRECTION_VECTORS[direction]
    vehicle = resolved_vehicle_spawn_position(config)
    delta_x = config.music_start_position.x - vehicle.x
    delta_z = config.music_start_position.z - vehicle.z
    starter_trigger_distance = delta_x * dx + delta_z * dz
    if starter_trigger_distance <= 0:
        raise ValueError(
            "vehicle_spawn_position is not behind music_start_position "
            f"for track_direction={direction}."
        )
    if starter_trigger_distance % VEHICLE_STEP_DISTANCE != 0:
        raise ValueError(
            "vehicle_spawn_position distance to music_start_position must be divisible "
            f"by vehicle_step_distance={VEHICLE_STEP_DISTANCE}."
        )
    return starter_trigger_distance // VEHICLE_STEP_DISTANCE


def total_track_length_from_layout(
    layout: LayoutResult,
    track_direction: str,
    music_start_position: BlockPosition,
) -> int:
    if not layout.cells:
        return 0

    direction = normalize_direction(track_direction)
    dx, dz = DIRECTION_VECTORS[direction]
    distances = [
        (cell.repeater_position.x - music_start_position.x) * dx
        + (cell.repeater_position.z - music_start_position.z) * dz
        for cell in layout.cells
    ]
    return max(0, max(distances)) + 2


def _prepare_chain_commands(
    config: PlaybackAssistModuleConfig,
    debug: PlaybackAssistDebugInfo,
) -> list[str]:
    return [
        (
            "execute as "
            f"@e[type=minecraft:armor_stand,tag={config.starter_tag}] "
            "at @s run setblock ~ ~ ~ air"
        ),
        f"kill @e[type=minecraft:minecart,tag={config.playback_vehicle_tag}]",
        _summon_vehicle(config),
        f"scoreboard players set {config.player_name} {config.count_objective} 0",
        (
            f"scoreboard players set start_music {config.count_objective} "
            f"{debug.start_music_count}"
        ),
        f"scoreboard players set end {config.count_objective} {debug.end_count}",
    ]


def _summon_vehicle(config: PlaybackAssistModuleConfig) -> str:
    position = resolved_vehicle_spawn_position(config)
    yaw = YAW_BY_DIRECTION[normalize_direction(config.track_direction)]
    return (
        "summon minecraft:minecart "
        f"{position.x} {position.y} {position.z} "
        "{"
        "NoGravity:1b,"
        f"Tags:[{_nbt_string(config.playback_vehicle_tag)}],"
        f"Rotation:[{yaw}f,0f]"
        "}"
    )


def _tp_vehicle(config: PlaybackAssistModuleConfig) -> str:
    return (
        f"execute as @e[tag={config.playback_vehicle_tag},type=minecraft:minecart] "
        "at @s run tp @s ^ ^ ^0.5"
    )


def _relative_setblock_command(
    command_block_position: BlockPosition,
    target_position: BlockPosition,
    block: str,
) -> str:
    return (
        "setblock "
        f"{_relative_coord(target_position.x - command_block_position.x)} "
        f"{_relative_coord(target_position.y - command_block_position.y)} "
        f"{_relative_coord(target_position.z - command_block_position.z)} "
        f"{_block_id(block)}"
    )


def _relative_coord(delta: int) -> str:
    if delta == 0:
        return "~"
    if delta > 0:
        return f"~{delta}"
    return f"~-{abs(delta)}"


def _local_position(
    config: PlaybackAssistModuleConfig,
    local_x: int,
    local_y: int,
) -> BlockPosition:
    origin = resolved_command_module_origin(config)
    return BlockPosition(
        origin.x + local_x,
        origin.y + local_y,
        origin.z,
    )


def above(position: BlockPosition) -> BlockPosition:
    return BlockPosition(position.x, position.y + 1, position.z)


def _command_block(command: str, facing: str | None = None) -> str:
    block = "command_block"
    if facing is not None:
        block += f"[facing={facing}]"
    return f"{block}{{Command:{_nbt_string(command)}}}"


def _chain_command_block(
    command: str,
    facing: str | None = None,
    auto: bool = False,
) -> str:
    block = "chain_command_block"
    if facing is not None:
        block += f"[facing={facing}]"
    auto_nbt = ",auto:1b" if auto else ""
    return f"{block}{{Command:{_nbt_string(command)}{auto_nbt}}}"


def _button_block(block: str, facing: str) -> str:
    return f"{_block_id(block)}[face=floor,facing={facing}]"


def _setblock(position: BlockPosition, block: str) -> str:
    return f"setblock {position.x} {position.y} {position.z} {_block_id(block)}"


def _block_id(block: str) -> str:
    if block.startswith("minecraft:"):
        return block
    return f"minecraft:{block}"


def _nbt_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
